  import aiImage from '@/assets/ai-course.jpg';
import pythonImage from '@/assets/python-course.jpg';
import reactImage from '@/assets/react-course.jpg';

  const managementCourses = [
    {
      id: 9,
      title: 'Workday HCM Administration',
      instructor: 'Michael Thompson',
      image: aiImage,
      duration: '8 weeks',
      students: '1,456',
      rating: 4.7,
      price: '$599',
      level: 'Professional',
      description: 'Complete Workday HCM configuration and administration',
      syllabus: [
        'Introduction to Workday HCM',
        'Core HCM Configuration',
        'Business Processes Setup',
        'Security Groups & Roles',
        'Workday Studio Basics',
        'Advanced Reporting & Dashboards',
        'Integrations Overview',
        'Final Capstone Project'
      ]
    },
    {
      id: 10,
      title: 'Digital Project Management',
      instructor: 'Lisa Wang',
      image: aiImage,
      duration: '6 weeks',
      students: '2,108',
      rating: 4.8,
      price: '$299',
      level: 'Beginner',
      description: 'Agile methodologies and modern project management tools',
      syllabus: [
        'Agile & Scrum Introduction',
        'Sprint Planning & Execution',
        'Project Lifecycle & Documentation',
        'Team Collaboration Tools',
        'Risk Management',
        'Project Closure Techniques'
      ]
    }
  ];

  const allCourses = [
    {
      id: 1,
      title: 'Generative AI & Machine Learning',
      instructor: 'Dr. Sarah Chen',
      image: aiImage,
      duration: '12 weeks',
      students: '2,847',
      rating: 4.9,
      price: '$299',
      level: 'Advanced',
      category: 'datascience',
      description: 'Deep dive into GPT, DALL-E, and custom AI model development, including RAG, AWS, and Azure integrations.',
      syllabus: [
        'Week 1: Introduction to AI & ML',
        'Week 2: Deep Learning with TensorFlow',
        'Week 3: Introduction to Generative Models',
        'Week 4: GPT and Transformer Architecture',
        'Week 5: Building Chatbots',
        'Week 6: Image Generation using GANs & DALL·E',
        'Week 7: Prompt Engineering',
        'Week 8: Model Deployment with Flask (AWS/Azure)',
        'Week 9: Real-time Use Cases & RAG Implementation',
        'Week 10: Custom Fine-tuning',
        'Week 11: Ethics & Bias in AI',
        'Week 12: Capstone Project',
      ]
    },
    {
      id: 1,
      title: 'Java Full Stack Development',
      instructor: 'Anjali Mehta',
      image: aiImage,
      duration: '18 weeks',
      students: '7,430',
      rating: 4.7,
      price: '$449',
      level: 'Intermediate',
      category: 'softwaredevelopment',
      description: 'Master Java, Spring Boot, Hibernate, and React to build scalable applications.',
      syllabus: [
        'Core Java',
        'OOP Concepts & Collections',
        'Spring Boot & MVC',
        'Hibernate ORM',
        'REST API Development',
        'Frontend with React',
        'JWT Authentication',
        'Maven & Jenkins',
        'Final Full Stack Project'
      ]
    },
    {
      id: 2,
      title: 'Python Full Stack Development',
      instructor: 'Mark Rodriguez',
      image: pythonImage,
      duration: '16 weeks',
      students: '5,234',
      rating: 4.8,
      price: '$399',
      level: 'Intermediate',
      category: 'softwaredevelopment',
      description: 'Build scalable web applications with Python, Django, and React',
      syllabus: [
        'HTML, CSS & JavaScript Basics',
        'Python Fundamentals',
        'Django Models & Views',
        'User Authentication',
        'REST APIs with Django',
        'React Basics & Hooks',
        'Connecting Django with React',
        'Deployment to Cloud',
        'Final Full Stack Project'
      ]
    },
    {
      id: 3,
      title: 'MERN Stack Web Development',
      instructor: 'Rahul Kapoor',
      image: aiImage,
      duration: '14 weeks',
      students: '6,100',
      rating: 4.6,
      price: '$379',
      level: 'Beginner to Advanced',
      category: 'softwaredevelopment',
      description: 'Learn MongoDB, Express, React, and Node.js to build modern web apps.',
      syllabus: [
        'JavaScript ES6+',
        'Node.js & Express Basics',
        'MongoDB & Mongoose',
        'React & React Router',
        'Context API & Hooks',
        'Authentication with JWT',
        'CRUD Operations',
        'API Integration',
        'Deployment & Hosting'
      ]
    }
    ,
    {
      id: 3,
      title: 'React.js & Next.js Mastery',
      instructor: 'Emily Johnson',
      image: reactImage,
      duration: '10 weeks',
      students: '3,921',
      rating: 4.9,
      price: '$349',
      level: 'Intermediate',
      category: 'softwaredevelopment',
      description: 'Modern frontend development with React ecosystem',
      syllabus: [
        'React Core Concepts',
        'Hooks Deep Dive',
        'Routing with React Router',
        'State Management with Redux',
        'Next.js Pages & SSR',
        'API Routes & Middleware',
        'Authentication with JWT',
        'SEO in Next.js',
        'Testing & Deployment'
      ]
    },
    {
      id: 4,
      title: 'AWS & Cloud Fundamentals',
      instructor: 'James Lee',
      image: aiImage,
      duration: '8 weeks',
      students: '1,820',
      rating: 4.7,
      price: '$299',
      level: 'Beginner',
      category: 'cloudcomputing',
      description: 'Learn cloud basics with real-time AWS deployment and services',
      syllabus: [
        'Cloud Basics & Deployment Models',
        'AWS Free Tier Setup',
        'EC2, S3, IAM',
        'RDS & DynamoDB',
        'VPC & Networking',
        'Serverless with Lambda',
        'Monitoring & Billing',
        'Hands-on Project'
      ]
    },
    {
      id: 5,
      title: 'Interior Design Basics',
      instructor: 'Clara Miles',
      image: pythonImage,
      duration: '6 weeks',
      students: '980',
      rating: 4.6,
      price: '$199',
      level: 'Beginner',
      category: 'fashion&interior',
      description: 'Foundational course in interior planning, colors, and furnishings',
      syllabus: [
        'Color Theory & Psychology',
        'Furniture Selection & Layout',
        'Lighting Techniques',
        'Textiles & Accessories',
        'Room-by-Room Planning',
        'Practical Design Project'
      ]
    },
    {
      id: 601,
      title: 'HR Generalist Training Program',
      instructor: 'Sonal Kapoor',
      image: "",
      duration: '8 weeks',
      students: '2,350',
      rating: 4.6,
      price: '$299',
      level: 'Beginner',
      category: 'hr',
      description: 'Comprehensive training for aspiring HR professionals covering recruitment, payroll, compliance, and more.',
      syllabus: [
        'Recruitment & Onboarding',
        'Payroll Processing',
        'Labor Laws & Compliance',
        'Performance Management',
        'HRIS Tools (Zoho, SAP)',
        'Exit Formalities',
        'Capstone: HR Audit Simulation'
      ]
    },
    {
      id: 602,
      title: 'Talent Acquisition & Recruitment',
      instructor: 'Rohit Sharma',
      image: "",
      duration: '6 weeks',
      students: '1,800',
      rating: 4.5,
      price: '$249',
      level: 'Intermediate',
      category: 'hr',
      description: 'Learn modern recruitment strategies, candidate screening, and ATS platforms.',
      syllabus: [
        'End-to-End Recruitment Process',
        'Job Descriptions & Sourcing',
        'Resume Screening Techniques',
        'Interviewing Skills',
        'Using ATS (Naukri, LinkedIn)',
        'Employer Branding',
        'KPI Tracking'
      ]
    },
    {
      id: 603,
      title: 'HR Analytics & Reporting',
      instructor: 'Meera Nair',
      image: "",
      duration: '5 weeks',
      students: '1,320',
      rating: 4.7,
      price: '$279',
      level: 'Advanced',
      category: 'hr',
      description: 'Leverage data-driven HR decision-making through analytics tools and dashboards.',
      syllabus: [
        'Introduction to HR Analytics',
        'KPIs & Metrics',
        'Dashboard Building in Excel',
        'Google Data Studio for HR',
        'Predictive Analytics',
        'Case Studies',
        'Project: HR Analytics Dashboard'
      ]
    },
    {
      id: 8,
      title: 'Spoken English Mastery',
      instructor: 'Alex Thompson',
      image: pythonImage,
      duration: '4 weeks',
      students: '3,650',
      rating: 4.6,
      price: '$149',
      level: 'Beginner',
      category: 'language',
      description: 'Improve fluency and confidence in English communication',
      syllabus: [
        'Grammar & Vocabulary',
        'Pronunciation Practice',
        'Speaking Fluency Drills',
        'Listening Comprehension',
        'Public Speaking Practice',
        'Mock Interviews'
      ]
    },
    {
      id: 11,
      title: 'Cloud Security Professional (CCSP)',
      instructor: 'Sarah Jenkins',
      image: reactImage,
      duration: '6 weeks',
      students: '750',
      rating: 4.8,
      price: '$499',
      level: 'Professional',
      category: 'cloudcomputing',
      description: 'Prepare for the CCSP certification with in-depth cloud security knowledge.',
      syllabus: [
        'Cloud Concepts, Architecture and Design',
        'Cloud Data Security',
        'Cloud Platform & Infrastructure Security',
        'Cloud Application Security',
        'Cloud Security Operations',
        'Legal, Risk and Compliance'
      ]
    },
    {
      id: 12,
      title: 'Hybrid Cloud & Multi-cloud Strategies',
      instructor: 'David Kim',
      image: aiImage,
      duration: '7 weeks',
      students: '620',
      rating: 4.7,
      price: '$379',
      level: 'Advanced',
      category: 'cloudcomputing',
      description: 'Design and implement robust hybrid and multi-cloud architectures.',
      syllabus: [
        'Introduction to Hybrid & Multi-cloud',
        'AWS Outposts & Azure Stack',
        'Google Anthos',
        'Network Connectivity in Hybrid Clouds',
        'Data Management Across Clouds',
        'Security Considerations',
        'Cost Optimization & Governance'
      ]
    },
    {
      id: 13,
      title: 'Cloud DevOps and Automation',
      instructor: 'Maria Sanchez',
      image: pythonImage,
      duration: '10 weeks',
      students: '1,500',
      rating: 4.9,
      price: '$450',
      level: 'Intermediate',
      category: 'clouddevops',
      description: 'Automate deployments and manage infrastructure as code in cloud environments.',
      syllabus: [
        'Introduction to DevOps',
        'Version Control with Git',
        'CI/CD Pipelines (Jenkins, GitLab CI)',
        'Infrastructure as Code (Terraform, CloudFormation)',
        'Configuration Management (Ansible, Chef)',
        'Containerization (Docker)',
        'Orchestration (Kubernetes)',
        'Monitoring & Logging'
      ]
    },
    {
      id: 14,
      title: 'CI/CD Pipeline Development',
      instructor: 'Robert Green',
      image: reactImage,
      duration: '6 weeks',
      students: '980',
      rating: 4.7,
      price: '$320',
      level: 'Intermediate',
      category: 'clouddevops',
      description: 'Build and optimize continuous integration and continuous delivery pipelines.',
      syllabus: [
        'Fundamentals of CI/CD',
        'Jenkins & GitLab CI Setup',
        'Automated Testing Integration',
        'Deployment Strategies',
        'Pipeline Security',
        'Monitoring CI/CD Pipelines'
      ]
    },
    {
      id: 15,
      title: 'Infrastructure as Code with Terraform',
      instructor: 'Elena Petrova',
      image: aiImage,
      duration: '5 weeks',
      students: '800',
      rating: 4.8,
      price: '$280',
      level: 'Intermediate',
      category: 'clouddevops',
      description: 'Provision and manage cloud infrastructure efficiently using Terraform.',
      syllabus: [
        'Introduction to IaC & Terraform',
        'Terraform Basics & HCL',
        'Managing AWS Resources with Terraform',
        'Terraform Modules',
        'State Management',
        'Advanced Terraform Concepts'
      ]
    },
    {
      id: 16,
      title: 'Kubernetes & Docker Fundamentals',
      instructor: 'Chris Evans',
      image: pythonImage,
      duration: '7 weeks',
      students: '1,200',
      rating: 4.9,
      price: '$390',
      level: 'Intermediate',
      category: 'clouddevops',
      description: 'Master containerization and orchestration with Docker and Kubernetes.',
      syllabus: [
        'Introduction to Containers & Docker',
        'Dockerizing Applications',
        'Docker Compose',
        'Introduction to Kubernetes',
        'Pods, Deployments, Services',
        'Kubernetes Networking & Storage',
        'Scaling & Self-Healing'
      ]
    },
    {
      id: 17,
      title: 'Cloud Migration and Management',
      instructor: 'Sophia Miller',
      image: reactImage,
      duration: '8 weeks',
      students: '700',
      rating: 4.6,
      price: '$420',
      level: 'Professional',
      category: 'clouddevops',
      description: 'Strategize and execute successful cloud migrations and ongoing cloud management.',
      syllabus: [
        'Cloud Migration Planning',
        'Migration Strategies (Lift & Shift, Replatform, Refactor)',
        'Data Migration Techniques',
        'Application Migration',
        'Cost Management in Cloud',
        'Cloud Governance & Compliance',
        'Cloud Operations & Monitoring'
      ]
    },
    {
      id: 18,
      title: 'AWS Certified Solutions Architect - Associate',
      instructor: 'John Doe',
      image: aiImage,
      duration: '10 weeks',
      students: '3000',
      rating: 4.9,
      price: '$500',
      level: 'Professional',
      category: 'certificationprep',
      description: 'Comprehensive preparation for the AWS Certified Solutions Architect - Associate exam.',
      syllabus: [
        'Designing Resilient Architectures',
        'Designing High-Performing Architectures',
        'Designing Secure Applications and Architectures',
        'Designing Cost-Optimized Architectures',
        'AWS Services Deep Dive'
      ]
    },
    {
      id: 19,
      title: 'Google Cloud Professional Cloud Architect',
      instructor: 'Jane Smith',
      image: pythonImage,
      duration: '10 weeks',
      students: '2500',
      rating: 4.8,
      price: '$550',
      level: 'Professional',
      category: 'certificationprep',
      description: 'Master Google Cloud Platform for the Professional Cloud Architect certification.',
      syllabus: [
        'Designing and planning a cloud solution architecture',
        'Managing and provisioning cloud infrastructure',
        'Designing for security and compliance',
        'Analyzing and optimizing technical and business processes',
        'Managing implementation',
        'Ensuring solution and operations reliability'
      ]
    },
    {
      id: 20,
      title: 'Microsoft Azure Administrator (AZ-104)',
      instructor: 'Mike Johnson',
      image: reactImage,
      duration: '8 weeks',
      students: '2800',
      rating: 4.7,
      price: '$450',
      level: 'Intermediate',
      category: 'certificationprep',
      description: 'Prepare for the AZ-104 exam and become a certified Azure Administrator.',
      syllabus: [
        'Manage Azure identities and governance',
        'Implement and manage storage',
        'Deploy and manage Azure compute resources',
        'Configure and manage virtual networking',
        'Monitor and back up Azure resources'
      ]
    },
    {
      id: 21,
      title: 'Certified Cloud Security Professional (CCSP)',
      instructor: 'Emily Davis',
      image: aiImage, // Using an existing image, replace with specific if available
      duration: '9 weeks',
      students: '1500',
      rating: 4.9,
      price: '$600',
      level: 'Advanced',
      category: 'certificationprep',
      description: 'In-depth preparation for the CCSP certification, focusing on cloud security architecture, design, and operations.',
      syllabus: [
        'Cloud Concepts, Architecture and Design',
        'Cloud Data Security',
        'Cloud Platform and Infrastructure Security',
        'Cloud Application Security',
        'Cloud Security Operations',
        'Legal, Risk and Compliance'
      ]
    },
    {
      id: 301,
      title: 'Cyber Security Fundamentals',
      instructor: 'Alice Thompson',
      image: "", // Replace with actual import or image path
      duration: '10 weeks',
      students: '3,210',
      rating: 4.7,
      price: '$299',
      level: 'Beginner',
      category: 'cybersecurity',
      description: 'Understand core cybersecurity concepts like threats, vulnerabilities, and defense mechanisms.',
      syllabus: [
        'Introduction to Cybersecurity',
        'Types of Threats & Attacks',
        'Security Principles & Frameworks',
        'Risk Assessment & Management',
        'Cryptography Basics',
        'Access Control & Authentication',
        'Secure Network Practices',
        'Incident Response Planning',
        'Final Project: Basic Security Audit'
      ]
    },
    {
      id: 302,
      title: 'Network Security & Firewalls',
      instructor: 'David Nguyen',
      image: "",
      duration: '8 weeks',
      students: '2,876',
      rating: 4.6,
      price: '$279',
      level: 'Intermediate',
      category: 'cybersecurity',
      description: 'Secure enterprise networks with firewalls, intrusion detection, and secure protocols.',
      syllabus: [
        'OSI & TCP/IP Security',
        'Firewalls: Types & Configuration',
        'VPNs and Secure Tunnels',
        'Intrusion Detection & Prevention',
        'Wireless Network Security',
        'Packet Analysis Tools',
        'Network Policy Implementation',
        'Security Monitoring',
        'Hands-on Network Lab'
      ]
    },
    {
      id: 303,
      title: 'Ethical Hacking & Penetration Testing',
      instructor: 'Sophia Lee',
      image: "",
      duration: '12 weeks',
      students: '4,502',
      rating: 4.8,
      price: '$349',
      level: 'Advanced',
      category: 'cybersecurity',
      description: 'Learn ethical hacking skills to test and strengthen systems against cyber attacks.',
      syllabus: [
        'Reconnaissance Techniques',
        'Scanning & Enumeration',
        'Vulnerability Assessment',
        'Exploitation Basics',
        'Web Application Attacks',
        'Metasploit Framework',
        'Social Engineering Techniques',
        'Report Writing',
        'Capstone: Penetration Test Report'
      ]
    },
    {
      id: 304,
      title: 'Cloud Security & Compliance',
      instructor: 'Rahul Mehta',
      image: "",
      duration: '9 weeks',
      students: '2,045',
      rating: 4.5,
      price: '$329',
      level: 'Intermediate',
      category: 'cybersecurity',
      description: 'Secure cloud environments with best practices and compliance standards like GDPR & HIPAA.',
      syllabus: [
        'Cloud Models & Shared Responsibility',
        'Cloud Threats & Risk Mitigation',
        'IAM in Cloud Platforms',
        'Data Security in Transit & at Rest',
        'Compliance Standards Overview',
        'Monitoring & Logging in Cloud',
        'Business Continuity & Disaster Recovery',
        'Cloud Provider Security Tools (AWS, Azure)',
        'Final Audit & Compliance Report'
      ]
    },
    {
      id: 401,
      title: 'Machine Learning Mastery',
      instructor: 'Dr. Ananya Sharma',
      image: "",
      duration: '10 weeks',
      students: '6,120',
      rating: 4.8,
      price: '$349',
      level: 'Intermediate',
      category: 'datascience',
      description: 'Master supervised and unsupervised learning using Python and Scikit-Learn.',
      syllabus: [
        'Intro to ML & Python Libraries',
        'Linear & Logistic Regression',
        'Decision Trees & Random Forests',
        'Model Evaluation & Cross Validation',
        'Unsupervised Learning: KMeans & PCA',
        'Model Tuning & Grid Search',
        'Real-world ML Projects',
        'Capstone: Build & Deploy ML Model'
      ]
    },
    {
      id: 402,
      title: 'Deep Learning with TensorFlow',
      instructor: 'Kevin Patel',
      image: "",
      duration: '12 weeks',
      students: '4,789',
      rating: 4.7,
      price: '$379',
      level: 'Advanced',
      category: 'datascience',
      description: 'Build neural networks and train models using TensorFlow and Keras.',
      syllabus: [
        'Neural Networks Foundations',
        'TensorFlow & Keras Setup',
        'CNNs for Image Processing',
        'RNNs & LSTMs for Sequences',
        'Transfer Learning',
        'Custom Model Deployment',
        'AI Ethics & Bias Mitigation',
        'Capstone: Deep Learning App'
      ]
    },
    {
      id: 403,
      title: 'Natural Language Processing (NLP)',
      instructor: 'Aisha Khan',
      image: "",
      duration: '9 weeks',
      students: '3,142',
      rating: 4.6,
      price: '$319',
      level: 'Intermediate',
      category: 'datascience',
      description: 'Process and analyze text data using modern NLP techniques and libraries.',
      syllabus: [
        'Text Preprocessing & Tokenization',
        'Bag of Words & TF-IDF',
        'Text Classification with ML',
        'Named Entity Recognition (NER)',
        'Word Embeddings (Word2Vec, GloVe)',
        'Sentiment Analysis',
        'Transformers & BERT Basics',
        'Capstone: NLP Chatbot'
      ]
    },
    {
      id: 404,
      title: 'Data Mining & Pattern Discovery',
      instructor: 'Suresh Iyer',
      image: "",
      duration: '8 weeks',
      students: '2,678',
      rating: 4.5,
      price: '$289',
      level: 'Beginner',
      category: 'datascience',
      description: 'Uncover patterns, trends, and anomalies in large datasets using mining algorithms.',
      syllabus: [
        'Data Preprocessing',
        'Frequent Itemsets & Association Rules',
        'Clustering & Hierarchical Methods',
        'Anomaly Detection',
        'Web Mining Techniques',
        'Text Mining Basics',
        'Use Cases in E-commerce & Healthcare',
        'Capstone: Market Basket Analysis'
      ]
    },
    {
      id: 405,
      title: 'End-to-End Data Science Projects',
      instructor: 'Emily Zhang',
      image: "",
      duration: '10 weeks',
      students: '3,765',
      rating: 4.7,
      price: '$359',
      level: 'Intermediate',
      category: 'datascience',
      description: 'Build real-world data science pipelines from data wrangling to model deployment.',
      syllabus: [
        'Project Planning & Data Collection',
        'Data Cleaning & Exploration',
        'Feature Engineering',
        'Model Building & Evaluation',
        'Visualization & Dashboarding',
        'ML Deployment with Flask',
        'Using Docker for Projects',
        'Capstone: Full DS Lifecycle'
      ]
    },

    {
      id: 501,
      title: 'Full Stack SAP Developer',
      instructor: 'Amit Sinha',
      image: "",
      duration: '14 weeks',
      students: '2,984',
      rating: 4.7,
      price: '$499',
      level: 'Advanced',
      category: 'sap',
      description: 'Become a full-stack SAP developer working with SAP UI5, Fiori, ABAP, and HANA.',
      syllabus: [
        'Intro to SAP Landscape & Architecture',
        'SAP UI5 & Fiori Front-End',
        'ABAP Programming for Backend',
        'SAP HANA Database Integration',
        'OData Services',
        'SAP Business Application Studio',
        'Project: End-to-End SAP App',
        'Deployment & Testing'
      ]
    },
    {
      id: 502,
      title: 'SAP FICO - Financial Accounting & Controlling',
      instructor: 'Priya Menon',
      image: "",
      duration: '10 weeks',
      students: '3,742',
      rating: 4.6,
      price: '$399',
      level: 'Intermediate',
      category: 'sap',
      description: 'Master financial accounting and controlling using SAP FICO.',
      syllabus: [
        'SAP ERP & Navigation',
        'General Ledger (GL)',
        'Accounts Payable/Receivable',
        'Asset Accounting',
        'Controlling (CO) Basics',
        'Internal Orders & Cost Centers',
        'Real-time Scenarios',
        'Capstone: FICO Configuration'
      ]
    },
    {
      id: 503,
      title: 'SAP S/4HANA – Enterprise Management',
      instructor: 'Nikhil Arora',
      image: "",
      duration: '12 weeks',
      students: '2,615',
      rating: 4.8,
      price: '$429',
      level: 'Intermediate',
      category: 'sap',
      description: 'Learn to manage enterprise-level operations with SAP S/4HANA.',
      syllabus: [
        'Overview of SAP S/4HANA',
        'Core Modules (MM, SD, PP)',
        'Data Modeling in HANA',
        'SAP Fiori Integration',
        'Embedded Analytics',
        'Workflow Management',
        'Real-World Case Studies',
        'Capstone: End-to-End ERP Flow'
      ]
    }



  ];